### ISSUE TITLE
Better documentation for other auth methods

### ISSUE THREAD

**Issue by NViviers** [Snazzah/stub#57]
I'd like to request some documentation or a simple guide to how exactly we should setup each authorization method? What should I set my redirect URI as for Discord integration, etc

**Comment by Snazzah** [comment]
All of the provided auth methods would have a redirect URI of `http://localhost:3000/api/auth/callback/[name]` with `[name]` being the name of the auth method in lowercase. So Discord would be `http://localhost:3000/api/auth/callback/discord`.

I'll add something to show the redirect URIs.

**Comment by NViviers** [comment]
I appreciate the help! :smile:
I'll leave this open for in case you want to use this to track it or something. Otherwise feel free to close it
